// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHdONM7qC3tax_2eIVZnRs7ZOXsx9SL8',
    appId: '1:740922529544:web:975796366729b2677d7ebd',
    messagingSenderId: '740922529544',
    projectId: 'climanews-8685c',
    authDomain: 'climanews-8685c.firebaseapp.com',
    storageBucket: 'climanews-8685c.firebasestorage.app',
    measurementId: 'G-DBY0Y6KQZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDTSgWyQ7UwtObvIIFYFOHWVKJgaDwC60',
    appId: '1:740922529544:android:478f91f5866a98b07d7ebd',
    messagingSenderId: '740922529544',
    projectId: 'climanews-8685c',
    storageBucket: 'climanews-8685c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN1ftMhz1yawMfffgbLBonEYN-NcGx1Cs',
    appId: '1:740922529544:ios:503f84279fe190727d7ebd',
    messagingSenderId: '740922529544',
    projectId: 'climanews-8685c',
    storageBucket: 'climanews-8685c.firebasestorage.app',
    iosBundleId: 'com.example.climaNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN1ftMhz1yawMfffgbLBonEYN-NcGx1Cs',
    appId: '1:740922529544:ios:503f84279fe190727d7ebd',
    messagingSenderId: '740922529544',
    projectId: 'climanews-8685c',
    storageBucket: 'climanews-8685c.firebasestorage.app',
    iosBundleId: 'com.example.climaNews',
  );
}
